<!DOCTYPE html>
<html lang="en"><head>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-html/tabby.min.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-0815c480559380816a4d1ea211a47e91.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.7.29">

  <title>EST014 - Estatística Multivariada I – Análise de Componentes Principais</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="../../site_libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="../../site_libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
        color: #aaaaaa;
      }
    pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
    div.sourceCode
      { color: #003b4f; background-color: #f1f3f5; }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #003b4f; } /* Normal */
    code span.al { color: #ad0000; } /* Alert */
    code span.an { color: #5e5e5e; } /* Annotation */
    code span.at { color: #657422; } /* Attribute */
    code span.bn { color: #ad0000; } /* BaseN */
    code span.bu { } /* BuiltIn */
    code span.cf { color: #003b4f; font-weight: bold; } /* ControlFlow */
    code span.ch { color: #20794d; } /* Char */
    code span.cn { color: #8f5902; } /* Constant */
    code span.co { color: #5e5e5e; } /* Comment */
    code span.cv { color: #5e5e5e; font-style: italic; } /* CommentVar */
    code span.do { color: #5e5e5e; font-style: italic; } /* Documentation */
    code span.dt { color: #ad0000; } /* DataType */
    code span.dv { color: #ad0000; } /* DecVal */
    code span.er { color: #ad0000; } /* Error */
    code span.ex { } /* Extension */
    code span.fl { color: #ad0000; } /* Float */
    code span.fu { color: #4758ab; } /* Function */
    code span.im { color: #00769e; } /* Import */
    code span.in { color: #5e5e5e; } /* Information */
    code span.kw { color: #003b4f; font-weight: bold; } /* Keyword */
    code span.op { color: #5e5e5e; } /* Operator */
    code span.ot { color: #003b4f; } /* Other */
    code span.pp { color: #ad0000; } /* Preprocessor */
    code span.sc { color: #5e5e5e; } /* SpecialChar */
    code span.ss { color: #20794d; } /* SpecialString */
    code span.st { color: #20794d; } /* String */
    code span.va { color: #111111; } /* Variable */
    code span.vs { color: #20794d; } /* VerbatimString */
    code span.wa { color: #5e5e5e; font-style: italic; } /* Warning */
  </style>
  <link rel="stylesheet" href="../../site_libs/revealjs/dist/theme/quarto-5389521b91c90b914e6de3488af1db39.css">
  <link href="../../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
<meta property="og:title" content="Análise de Componentes Principais – EST014 - Estatística Multivariada I">
<meta property="og:site_name" content="EST014 - Estatística Multivariada I">
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" data-background-image="../../images/back.png" data-background-opacity="0.3" data-background-size="cover" class="quarto-title-block center">
  <h1 class="title">Análise de Componentes Principais</h1>

<div class="quarto-title-authors">
</div>

</section>
<section id="introdução" class="slide level2">
<h2>Introdução</h2>
<p>Um problema central na análise de dados multivariados é a <strong>redução da dimensionalidade:</strong> é possível descrever com precisão a informação contida nos dados mensurados em <span class="math inline">\(p\)</span> variáveis utilizando um conjunto <span class="math inline">\(r &lt; p\)</span> de novas variáveis, perdendo a menor quantidade de informação possível?</p>
<div class="fragment">
<p>A <strong>análise de componentes principais</strong> tem este objetivo: dadas <span class="math inline">\(n\)</span> observações de <span class="math inline">\(p\)</span> variáveis, se analisa se é possível representar adequadamente esta informação com um número menor de variáveis construídas como <strong>combinações lineares</strong> das variáveis originais.</p>
</div>
</section>
<section id="o-problema" class="slide level2">
<h2>O Problema…</h2>
<p>Dado um conjunto de variáveis <span class="math inline">\(\mathbf{x} = [X_1 \hspace{0.1cm} X_2 \hspace{0.1cm} \cdots \hspace{0.1cm} X_p]^t\)</span>, podemos encontrar outro conjunto de variáveis <span class="math inline">\(\mathbf{y} = [Y_1 \hspace{0.1cm} Y_2 \hspace{0.1cm} \cdots \hspace{0.1cm} Y_r]^t\)</span>, dadas por</p>
<p><span class="math display">\[Y_i= \displaystyle{\sum_{j=1}^p a_{ij}X_j}, \,\, i = 1, \cdots, r &lt; p\]</span></p>
<p>de tal forma que a informação contida em <span class="math inline">\(\mathbf{x}\)</span> esteja sendo bem representada por <span class="math inline">\(\mathbf{y}\)</span>?</p>
</section>
<section id="algumas-questões" class="slide level2">
<h2>Algumas questões</h2>
<p><br></p>
<p>Vamos encontrar combinações lineares para representar informação.</p>
<div class="fragment">
<p style="text-align: center;">
<span style="font-size:50px;">🤔</span> O que é <strong>informação</strong>?
</p>
</div>
<div class="fragment">
<p><strong>Informação <span class="math inline">\(\Longrightarrow\)</span> Variância: quanto maior a variabilidade, maior a informação contida nos dados, maior a variância dos dados</strong></p>
</div>
</section>
<section id="algumas-questões-1" class="slide level2">
<h2>Algumas questões</h2>
<p><br></p>
<p>Outra questão importante:</p>
<div class="fragment">
<p style="text-align: center;">
<span style="font-size:50px;">🤔</span> O que é <strong>uma boa representação da informação</strong>?
</p>
</div>
<div class="fragment">
<p><strong>Boa representação da informação <span class="math inline">\(\Longrightarrow\)</span> tomar as componentes de <span class="math inline">\(\mathbf{y}\)</span> que assegurem uma variância similar à de <span class="math inline">\(\mathbf{x}\)</span></strong></p>
</div>
</section>
<section id="esquematicamente" class="slide level2">
<h2>Esquematicamente</h2>
<p>Nestas condições, temos que buscar <strong>combinações lineares</strong> <span class="math inline">\(\mathbf{y}\)</span> das variáveis <span class="math inline">\(\mathbf{x}\)</span> de forma que se <em>maximize</em> a <strong>variância</strong></p>
<div class="fragment">
<style type="text/css">
.tg  {border-collapse:collapse;border-color:white;border-spacing:0;border-style:solid;border-width:1px;margin:0px auto;}
.tg td{border-style:solid;border-width:0px;font-family:Arial, sans-serif;font-size:36px;overflow:hidden;
  padding:10px 5px;word-break:normal;}
.tg th{border-style:solid;border-width:0px;font-family:Arial, sans-serif;font-size:36px;font-weight:normal;
  overflow:hidden;padding:10px 5px;word-break:normal;}
.tg .tg-c3ow{border-color:white;text-align:center;vertical-align:top}
.tg .tg-7btt{border-color:white;font-weight:bold;text-align:center;vertical-align:top}
</style>
<table class="tg">
<thead>
<tr>
<th class="tg-7btt">
Variáveis Originais
</th>
<th class="tg-c3ow">
</th>
<th class="tg-7btt">
Combinações Lineares
</th>
</tr>
</thead>
<tbody>
<tr>
<td class="tg-c3ow">
<span class="math inline">\(X_1\)</span>
</td>
<td class="tg-c3ow">
</td>
<td class="tg-c3ow">
<span class="math inline">\(Y_1\)</span>
</td>
</tr>
<tr>
<td class="tg-c3ow">
<span class="math inline">\(X_2\)</span>
</td>
<td class="tg-c3ow">
</td>
<td class="tg-c3ow">
<span class="math inline">\(Y_2\)</span>
</td>
</tr>
<tr>
<td class="tg-c3ow">
<span class="math inline">\(\vdots\)</span>
</td>
<td class="tg-c3ow">
</td>
<td class="tg-c3ow">
<span class="math inline">\(\vdots\)</span>
</td>
</tr>
<tr>
<td class="tg-c3ow">
<span class="math inline">\(X_{r}\)</span>
</td>
<td class="tg-c3ow">
<span class="math inline">\(\Longrightarrow\)</span>
</td>
<td class="tg-c3ow">
<span class="math inline">\(Y_r\)</span>
</td>
</tr>
<tr>
<td class="tg-c3ow">
<span class="math inline">\(\vdots\)</span>
</td>
<td class="tg-c3ow">
</td>
<td class="tg-c3ow">
<span class="math inline">\(\vdots\)</span>
</td>
</tr>
<tr>
<td class="tg-c3ow">
<span class="math inline">\(X_p\)</span>
</td>
<td class="tg-c3ow">
</td>
<td class="tg-c3ow">
<span class="math inline">\(Y_{p}\)</span>
</td>
</tr>
</tbody>
</table>
</div>
<div class="fragment">
<p style="text-align: center;">
<span class="math inline">\(\rm{Var}[\mathbf{y}]\)</span>: Máxima
</p>
</div>
</section>
<section id="esquematicamente-1" class="slide level2">
<h2>Esquematicamente</h2>
<p>Ideia básica da técnica de Análise de Componentes Principais:</p>
<div class="fragment">
<style type="text/css">
.tg  {border-collapse:collapse;border-spacing:0;margin:0px auto;}
.tg td{border-color:white;border-style:solid;border-width:1px;font-family:Arial, sans-serif;font-size:36px;
  overflow:hidden;padding:10px 5px;word-break:normal;}
.tg th{border-color:white;border-style:solid;border-width:1px;font-family:Arial, sans-serif;font-size:36px;
  font-weight:normal;overflow:hidden;padding:10px 5px;word-break:normal;}
.tg .tg-dxqr{border-color:white;color:#fe0000;text-align:center;vertical-align:top}
.tg .tg-c3ow{border-color:white;text-align:center;vertical-align:top}
.tg .tg-7btt{border-color:white;font-weight:bold;text-align:center;vertical-align:top}
</style>
<table class="tg">
<thead>
<tr>
<th class="tg-c3ow">
Variáveis Originais
</th>
<th class="tg-c3ow">
</th>
<th class="tg-c3ow">
Componentes Principais
</th>
</tr>
</thead>
<tbody>
<tr>
<td class="tg-c3ow">
<span class="math inline">\(X_1\)</span>
</td>
<td class="tg-7btt">
ACP
</td>
<td class="tg-dxqr">
<span class="math inline">\(Y_1\)</span>
</td>
</tr>
<tr>
<td class="tg-c3ow">
<span class="math inline">\(X_2\)</span>
</td>
<td class="tg-c3ow">
<span class="math inline">\(\Longrightarrow\)</span>
</td>
<td class="tg-dxqr">
<span class="math inline">\(Y_2\)</span>
</td>
</tr>
<tr>
<td class="tg-c3ow">
<span class="math inline">\(\vdots\)</span>
</td>
<td class="tg-c3ow">
</td>
<td class="tg-dxqr">
<span class="math inline">\(\vdots\)</span>
</td>
</tr>
<tr>
<td class="tg-c3ow">
<span class="math inline">\(X_{p}\)</span>
</td>
<td class="tg-c3ow">
</td>
<td class="tg-dxqr">
<span class="math inline">\(Y_r\)</span>
</td>
</tr>
<tr>
<td class="tg-c3ow">
</td>
<td class="tg-c3ow">
</td>
<td class="tg-c3ow">
<span class="math inline">\(\vdots\)</span>
</td>
</tr>
<tr>
<td class="tg-c3ow">
</td>
<td class="tg-c3ow">
</td>
<td class="tg-c3ow">
<span class="math inline">\(Y_{p}\)</span>
</td>
</tr>
</tbody>
</table>
</div>
<div class="fragment">
<p style="text-align: center;">
<span class="math inline">\(r\)</span> primeiras componentes resumam, por exemplo, 80% do comportamento geral das <span class="math inline">\(p\)</span> variáveis originais
</p>
</div>
</section>
<section id="principais-objetivos" class="slide level2">
<h2>Principais objetivos</h2>
<ul>
<li>Redução da dimensionalidade dos dados, projetando-os em uma dimensão <span class="math inline">\(r &lt; p\)</span>;</li>
</ul>

<img data-src="../..\images/CP/red_dimens.png" class="quarto-figure quarto-figure-center r-stretch"></section>
<section id="principais-objetivos-1" class="slide level2">
<h2>Principais objetivos</h2>
<ul>
<li>Obtenção de combinações interpretáveis: determinar índices e produzir escores com base nos resultados avaliados para as <span class="math inline">\(p\)</span> variáveis;</li>
</ul>

<img data-src="../..\images/CP/idh.png" class="quarto-figure quarto-figure-center r-stretch"></section>
<section id="principais-objetivos-2" class="slide level2">
<h2>Principais objetivos</h2>
<ul>
<li>Descrição e entendimento da estrutura de correlação entre as variáveis, através de algumas combinações lineares das mesmas.</li>
</ul>

<img data-src="../..\images/CP/fig_pca.png" class="quarto-figure quarto-figure-center r-stretch"></section>
<section id="componentes-principais-o-que-são" class="slide level2">
<h2>Componentes Principais: o que são?</h2>
<p><strong>Algebricamente:</strong> são combinações lineares das <span class="math inline">\(p\)</span> variáveis originais, <span class="math inline">\(X_1, X_2, \cdots, X_p\)</span>.</p>
<div class="fragment">
<p><strong>Geometricamente:</strong> são as coordenadas dos pontos amostrais em um sistema de eixos obtido pela rotação do sistema de eixos original, na direção de variabilidade máxima.</p>
<p style="text-align: center;">
<a href="https://setosa.io/ev/principal-component-analysis"><span style="font-size:100px;">🔎</span></a>
</p>
</div>
</section>
<section id="componentes-principais-alguns-comentários" class="slide level2">
<h2>Componentes Principais: alguns comentários</h2>
<ul>
<li>Não pressupõe normalidade dos dados, embora componentes derivadas de populações normais tenham interpretações úteis.</li>
</ul>
<div class="fragment">
<ul>
<li>Com frequência, revela relações insuspeitas. Pode permitir interpretações que não seriam obtidas preliminarmente.</li>
</ul>
</div>
<div class="fragment">
<ul>
<li>Em algumas aplicações, os componentes da ACP configuram o objetivo final do estudo. Em outras, servem como passo intermediário para realização de outras análises, como regressão, classificação, agrupamento, etc…</li>
</ul>
</div>
</section>
<section id="componentes-principais-como-obtê-los" class="slide level2">
<h2>Componentes Principais: como obtê-los?</h2>
<ul>
<li>Sejam <span class="math inline">\(X_1, \hspace{0.1cm} X_2, \hspace{0.1cm} \cdots, \hspace{0.1cm} X_p\)</span> as variáveis originais</li>
</ul>
<div class="fragment">
<ul>
<li>A ideia é encontrar um novo conjunto de variáveis <span class="math inline">\(Y_1, \hspace{0.1cm} Y_2, \hspace{0.1cm} \cdots, \hspace{0.1cm} Y_p\)</span>, tais que:</li>
</ul>
<p><span class="math display">\[\textrm{Var}[Y_1] \geqslant \textrm{Var}[Y_2] \geqslant \cdots \geqslant \textrm{Var}[Y_p]\]</span></p>
</div>
<div class="fragment">
<ul>
<li>Vamos tomar cada nova variável <span class="math inline">\(Y_i\)</span>, <span class="math inline">\(i = 1, \cdots, p\)</span>, como uma combinação linear das variáveis originais <span class="math inline">\(\mathbf{x}\)</span>:</li>
</ul>
<p><span class="math display">\[Y_i = a_{i1}X_1 + a_{i2}X_2 + \cdots + a_{ip}X_p = \mathbf{a}_i^t \mathbf{x}\]</span></p>
</div>
</section>
<section id="componentes-principais-como-obtê-los-1" class="slide level2">
<h2>Componentes Principais: como obtê-los?</h2>
<ul>
<li>Para fixar problemas de escala, adicionamos uma primeira restrição aos vetores <span class="math inline">\(\mathbf{a}_i\)</span>:</li>
</ul>
<p><span class="math display">\[\mathbf{a}_i^t \mathbf{a}_i = \displaystyle{ \sum_{j=1}^p a_{ij}^2} = 1\]</span></p>
<div class="fragment">
<ul>
<li>Para evitar que duas variáveis <span class="math inline">\(Y_i\)</span> e <span class="math inline">\(Y_k\)</span>, <span class="math inline">\(i \neq k\)</span>, <span class="math inline">\(i,k = 1, \cdots, p\)</span>, compartilhem informação, adicionamos uma segunda restrição aos vetores <span class="math inline">\(\mathbf{a}_i\)</span>:</li>
</ul>
<p><span class="math display">\[\mathbf{a}_i^t \mathbf{a}_k = \displaystyle{ \sum_{j=1}^p a_{ij}a_{kj}}  = 0\]</span></p>
</div>
</section>
<section id="componentes-principais-como-obtê-los-2" class="slide level2">
<h2>Componentes Principais: como obtê-los?</h2>
<p><br></p>
<p><br></p>
<p style="text-align: center;">
💡 <strong>Garantia:</strong> ortogalidade, componentes não correlacionadas, independência
</p>
</section>
<section id="componentes-principais-como-obtê-los-3" class="slide level2">
<h2>Componentes Principais: como obtê-los?</h2>
<p style="text-align: center; color: red;">
<strong>Primeira Componente Principal</strong>
</p>
<p><span class="math display">\[Y_1 = a_{11}X_1 + a_{12}X_2 + \cdots + a_{1p}X_p = \boldsymbol{a}_1^t \mathbf{x}\]</span></p>
<div class="fragment">
<p><strong>Objetivo:</strong> Encontrar <span class="math inline">\(\boldsymbol{a}_1^t = [a_{11} \hspace{0.3cm} a_{12} \hspace{0.3cm} \cdots \hspace{0.3cm} a_{1p}]^t\)</span> tal que:</p>
<p style="text-align: center; color: red;">
<strong><span class="math inline">\(\rm{Var}[Y_1]\)</span> seja máxima</strong>
</p>
</div>
<div class="fragment">
<p>Sujeita à restrição:</p>
<p><span class="math display">\[\boldsymbol{a}_1^t \boldsymbol{a}_1 = a_{11}^2 + a_{12}^2 + \cdots + a_{1p}^2 = 1\]</span></p>
</div>
</section>
<section id="componentes-principais-como-obtê-los-4" class="slide level2">
<h2>Componentes Principais: como obtê-los?</h2>
<p style="text-align: center; color: red;">
<strong>Segunda Componente Principal</strong>
</p>
<p><span class="math display">\[Y_2 = a_{21}X_1 + a_{22}X_2 + \cdots + a_{2p}X_p = \boldsymbol{a}_2^t \mathbf{x}\]</span></p>
<div class="fragment">
<p><strong>Objetivo:</strong> Encontrar <span class="math inline">\(\boldsymbol{a}_2^t = [a_{21} \hspace{0.3cm} a_{22} \hspace{0.3cm} \cdots \hspace{0.3cm} a_{2p}]^t\)</span> tal que:</p>
<p style="text-align: center; color: red;">
<strong><span class="math inline">\(\rm{Var}[Y_2]\)</span> seja máxima</strong>
</p>
</div>
<div class="fragment">
<p>Sujeita à restrição:</p>
<p><span class="math display">\[\boldsymbol{a}_2^t \boldsymbol{a}_2 = a_{21}^2 + a_{22}^2 + \cdots + a_{2p}^2 = 1\]</span></p>
<p><span class="math display">\[\rm{Cov}[Y_1,Y_2] = 0\]</span></p>
</div>
</section>
<section id="componentes-principais-como-obtê-los-5" class="slide level2">
<h2>Componentes Principais: como obtê-los?</h2>
<p style="text-align: center; color: red;">
<strong>i-ésima Componente Principal</strong>
</p>
<p><span class="math display">\[Y_i = a_{i1}X_1 + a_{i2}X_2 + \cdots + a_{ip}X_p = \boldsymbol{a}_i^t \mathbf{x}\]</span></p>
<div class="fragment">
<p><strong>Objetivo:</strong> Encontrar <span class="math inline">\(\boldsymbol{a}_i^t = [a_{i1} \hspace{0.3cm} a_{i2} \hspace{0.3cm} \cdots \hspace{0.3cm} a_{ip}]^t\)</span> tal que:</p>
<p style="text-align: center; color: red;">
<strong><span class="math inline">\(\rm{Var}[Y_i]\)</span> seja máxima</strong>
</p>
</div>
<div class="fragment">
<p>Sujeita à restrição:</p>
<p><span class="math display">\[\boldsymbol{a}_i^t \boldsymbol{a}_i =  a_{i1}^2 + a_{i2}^2 + \cdots + a_{ip}^2 = 1\]</span></p>
<p><span class="math display">\[\rm{Cov}[Y_,Y_k] = 0, \text{para  } k &lt; i\]</span></p>
</div>
</section>
<section id="a-escolha-dos-vetores-boldsymbola_i" class="slide level2">
<h2>A escolha dos vetores <span class="math inline">\(\boldsymbol{a}_i\)</span></h2>
<ul>
<li>Considere o vetor aleatório p-variado <span class="math inline">\(\mathbf{x} = [X_1 \hspace{0.3cm} X_2 \hspace{0.3cm} \cdots \hspace{0.3cm} X_p]^t\)</span> com vetor de médias <span class="math inline">\(\boldsymbol{\mu}\)</span> e matriz de covariâncias <span class="math inline">\(\boldsymbol{\Sigma}\)</span>, positiva definida (todos os seus autovalores são positivos), sendo</li>
</ul>
<p><span class="math display">\[\boldsymbol{\mu} = [\mu_1 \hspace{0.3cm} \mu_2 \hspace{0.3cm} \cdots \hspace{0.3cm} \mu_p]^t \hspace{0.5cm} \textrm{e} \hspace{0.5cm}
\boldsymbol{\Sigma} = \left[ \begin{array}{cccc} \sigma_{11} &amp; \sigma_{12} &amp; \cdots &amp; \sigma_{1p}
\\ \sigma_{21} &amp; \sigma_{22} &amp; \cdots &amp; \sigma_{2p}
\\ \vdots &amp; \vdots &amp; \ddots &amp; \vdots
\\ \sigma_{p1} &amp; \sigma_{p2} &amp; \cdots &amp; \sigma_{pp} \end{array} \right]\]</span></p>
<div class="fragment">
<ul>
<li>Para determinação dos componentes principais, com base no que foi exposto, usaremos o seguinte teorema:</li>
</ul>
</div>
</section>
<section id="a-escolha-dos-vetores-boldsymbola_i-1" class="slide level2">
<h2>A escolha dos vetores <span class="math inline">\(\boldsymbol{a}_i\)</span></h2>
<p><strong>Teorema - Maximização de formas quadráticas:</strong> Seja <span class="math inline">\(\boldsymbol{B}\)</span> uma matriz positiva definida com autovalores <span class="math inline">\(\lambda_1 \geqslant \lambda_2 \geqslant \cdots \geqslant \lambda_p &gt; 0\)</span> e autovetores associados normalizados <span class="math inline">\({\boldsymbol{e}_1, \boldsymbol{e}_2, \cdots, \boldsymbol{e}_p}\)</span>. Então:</p>
<p><span class="math display">\[\max_{\mathbf{x} \neq \boldsymbol{0}} \dfrac{\mathbf{x}^t \boldsymbol{B} \mathbf{x}}{\mathbf{x}^t \mathbf{x}} =  \lambda_1, \text{ obtido quando } \mathbf{x} = \boldsymbol{e}_1;\]</span></p>
<p><span class="math display">\[\min_{\mathbf{x} \neq \boldsymbol{0}} \dfrac{\mathbf{x}^t \boldsymbol{B} \mathbf{x}}{\mathbf{x}^t \mathbf{x}} =  \lambda_p, \text{ obtido quando } \mathbf{x} = \boldsymbol{e}_p.\]</span></p>
<div class="fragment">
<ul>
<li>Adicionalmente,</li>
</ul>
<p><span class="math display">\[\max_{\mathbf{x} \perp \boldsymbol{e}_1, \boldsymbol{e}_1, \cdots, \boldsymbol{e}_k} \dfrac{\mathbf{x}^t \boldsymbol{B} \mathbf{x}}{\mathbf{x}^t \mathbf{x}} =  \lambda_{k+1}, \text{ obtido quando } \mathbf{x} = \boldsymbol{e}_{k+1}.\]</span></p>
</div>
</section>
<section id="a-escolha-dos-vetores-boldsymbola_i-2" class="slide level2">
<h2>A escolha dos vetores <span class="math inline">\(\boldsymbol{a}_i\)</span></h2>
<p>Assim, no contexto de componentes principais, seja <span class="math inline">\(\mathbf{x} = [X_1 \hspace{0.3cm} X_2 \hspace{0.3cm} \cdots \hspace{0.3cm} X_p]^t\)</span> um vetor aleatório. Seja <span class="math inline">\(\boldsymbol{\Sigma}\)</span> a matriz de variâncias e covariâncias e <span class="math inline">\((\lambda_1, \boldsymbol{e}_1)\)</span>, <span class="math inline">\((\lambda_2, \boldsymbol{e}_2)\)</span>, …, <span class="math inline">\((\lambda_p, \boldsymbol{e}_p)\)</span> seus autovalores e autovetores, tal que <span class="math inline">\(\lambda_1 \geqslant \lambda_2 \geqslant \cdots \geqslant \lambda_p &gt; 0\)</span>. Então:</p>
<p><span class="math display">\[\max_{\boldsymbol{a} \neq \boldsymbol{0}} \dfrac{\boldsymbol{a}^t \boldsymbol{\Sigma} \boldsymbol{a}}{\boldsymbol{a}^t \boldsymbol{a}} = \max_{\boldsymbol{a} \neq \boldsymbol{0}}(\boldsymbol{a}^t \boldsymbol{\Sigma} \boldsymbol{a}) = \lambda_1, \text{ obtido quando } \boldsymbol{a} = \boldsymbol{e}_1;\]</span></p>
<p><span class="math display">\[\min_{\boldsymbol{a} \neq \boldsymbol{0}} \dfrac{\boldsymbol{a}^t \boldsymbol{\Sigma} \boldsymbol{a}}{\boldsymbol{a}^t \boldsymbol{a}} = \min_{\boldsymbol{a} \neq \boldsymbol{0}}(\boldsymbol{a}^t \boldsymbol{\Sigma} \boldsymbol{a}) = \lambda_p, \text{ obtido quando } \boldsymbol{a} = \boldsymbol{e}_p.\]</span></p>
</section>
<section id="a-escolha-dos-vetores-boldsymbola_i-3" class="slide level2">
<h2>A escolha dos vetores <span class="math inline">\(\boldsymbol{a}_i\)</span></h2>
<ul>
<li>Adicionalmente,</li>
</ul>
<p><span class="math display">\[\max_{\boldsymbol{a} \perp \boldsymbol{e}_1, \boldsymbol{e}_1, \cdots, \boldsymbol{e}_k} \dfrac{\boldsymbol{a}^t \boldsymbol{\Sigma} {\boldsymbol a}}{\boldsymbol{a}^t \boldsymbol{a}} = \max_{\boldsymbol{a} \perp \boldsymbol{e}_1, \boldsymbol{e}_1, \cdots, \boldsymbol{e}_k}(\boldsymbol{a}^t \boldsymbol{\Sigma} \boldsymbol{a})= \lambda_{k+1}, \text{ obtido quando } \boldsymbol{a} = \boldsymbol{e}_{k+1}.\]</span></p>
</section>
<section id="a-escolha-dos-vetores-boldsymbola_i-4" class="slide level2">
<h2>A escolha dos vetores <span class="math inline">\(\boldsymbol{a}_i\)</span></h2>
<ul>
<li>Uma escolha interessante para os vetores de constantes <span class="math inline">\({\boldsymbol{a}_i}\)</span>, <span class="math inline">\(i = 1, \cdots, p\)</span> são os <strong>autovetores normalizados</strong> <span class="math inline">\({\boldsymbol{e}_i}\)</span> da matriz <span class="math inline">\(\boldsymbol{\Sigma}\)</span>.</li>
</ul>
<div class="fragment">
<ul>
<li>Dessa forma, podemos definir a <span class="math inline">\(i\)</span>-ésima componente principal da matriz <span class="math inline">\(\boldsymbol{\Sigma}\)</span>, <span class="math inline">\(i = 1, \cdots, p\)</span> como sendo</li>
</ul>
</div>
<div class="fragment">
<p><span class="math display">\[Y_i = {\boldsymbol{e}_i^t}\mathbf{x} =  e_{i1}X_1 + e_{i2}X_2 + \cdots + e_{ip}X_p\]</span></p>
</div>
</section>
<section id="componentes-principais-propriedades" class="slide level2">
<h2>Componentes Principais: propriedades</h2>
<ul>
<li>A esperança e a variância da componente <span class="math inline">\(Y_i\)</span> são respectivamente dadas por:</li>
</ul>
<p><span class="math display">\[
\begin{eqnarray*}
E[Y_i] &amp;=&amp; E[e_{i1}X_1 + e_{i2}X_2 + \cdots + e_{ip}X_p]  \nonumber \\
&amp;=&amp; e_{i1}E[X_1] + e_{i2}E[X_2] + \cdots + e_{ip}E[X_p]  \nonumber \\
&amp;=&amp; e_{i1}\mu_1 + e_{i2}\mu_2 + \cdots + e_{ip}\mu_p \nonumber \\
&amp;=&amp; {\boldsymbol{e}_i^t}{\boldsymbol{\mu}} \nonumber
\end{eqnarray*}
\]</span></p>
<div class="fragment">
<p><span class="math display">\[ \textrm{Var}[Y_i] = \textrm{Var}[{\boldsymbol{e}_i^t}\mathbf{x}] = {\boldsymbol{e}_i^t} \textrm{Var}[\mathbf{x}] {\boldsymbol{e}_i}
=  {\boldsymbol{e}_i^t} \boldsymbol{\Sigma} {\boldsymbol{e}_i} = {\boldsymbol{e}_i^t} \lambda_i {\boldsymbol{e}_i} =   
{\boldsymbol{e}_i^t} {\boldsymbol{e}_i}\lambda_i = \lambda_i \]</span></p>
</div>
</section>
<section id="na-forma-matricial" class="slide level2">
<h2>Na forma matricial</h2>
<ul>
<li>Sejam <span class="math inline">\(\boldsymbol{O}\)</span> a matriz dos autovetores normalizados da matriz <span class="math inline">\(\boldsymbol{\Sigma}\)</span>, isto é,</li>
</ul>
<p><span class="math display">\[\boldsymbol{O} = \left[ \begin{array}{cccc} e_{11} &amp; e_{21} &amp; \cdots &amp; e_{p1}
\\ e_{12} &amp; e_{22} &amp; \cdots &amp; e_{p2}
\\ \vdots &amp; \vdots &amp; \ddots &amp; \vdots
\\ e_{1p} &amp; e_{2p} &amp; \cdots &amp; e_{pp} \end{array} \right] = [{\boldsymbol{e}_1} \hspace{0.5cm} {\boldsymbol{e}_2}
\hspace{0.5cm} \cdots \hspace{0.5cm} {\boldsymbol{e}_p}]\]</span></p>
<p>e <span class="math inline">\(\boldsymbol{y}\)</span> o vetor das componentes principais. Então, <span class="math inline">\(\boldsymbol{y} = \boldsymbol{O}^t \mathbf{x}\)</span> e a matriz de covariâncias de <span class="math inline">\(\boldsymbol{y}\)</span> será:</p>
<p><span class="math display">\[\textrm{Var}[\boldsymbol{y}] = \textrm{Var}[\boldsymbol{O}^t \mathbf{x}] =  \boldsymbol{O}^t \textrm{Var}[\mathbf{x}] \boldsymbol{O} =
\boldsymbol{O}^t \boldsymbol{\Sigma} \boldsymbol{O} = \boldsymbol{\Lambda}\]</span></p>
</section>
<section id="na-forma-matricial-1" class="slide level2">
<h2>Na forma matricial</h2>
<p>sendo</p>
<p><span class="math display">\[\boldsymbol{\Lambda} = \left[ \begin{array}{cccc} \lambda_1 &amp; 0 &amp; \cdots &amp; 0
\\ 0 &amp; \lambda_2 &amp; \cdots &amp; 0
\\ \vdots &amp; \vdots &amp; \ddots &amp; \vdots
\\ 0 &amp; 0 &amp; \cdots &amp; \lambda_p \end{array} \right] \]</span></p>
<p>ou ainda, <span class="math inline">\(\boldsymbol{\Sigma} = \boldsymbol{O} \boldsymbol{\Lambda} \boldsymbol{O}^t = \displaystyle \sum_{i=1}^p \lambda_i \boldsymbol{e}_i \boldsymbol{e}_i^t\)</span>, uma vez que <span class="math inline">\(\boldsymbol{O}\)</span> é uma matriz ortogonal tal que <span class="math inline">\(\boldsymbol{O} \boldsymbol{O}^t = \boldsymbol{O}^t \boldsymbol{O} = \boldsymbol{I}\)</span>. Estes resultados são conhecidos como <strong>Teorema da decomposição espectral</strong>.</p>
</section>
<section id="variabilidade-explicada" class="slide level2">
<h2>Variabilidade explicada</h2>
<style type="text/css">
.tg  {border:none;border-collapse:collapse;border-spacing:0;margin:0px auto;}
.tg td{border-style:solid;border-width:0px;font-family:Arial, sans-serif;font-size:36px;overflow:hidden;
  padding:10px 5px;word-break:normal;}
.tg th{border-style:solid;border-width:0px;font-family:Arial, sans-serif;font-size:36px;font-weight:normal;
  overflow:hidden;padding:10px 5px;word-break:normal;}
.tg .tg-c3ow{border-color:inherit;text-align:center;vertical-align:top}
</style>
<table class="tg">
<thead>
<tr>
<th class="tg-c3ow">
Variável
</th>
<th class="tg-c3ow">
Variância
</th>
<th class="tg-c3ow">
Componente
</th>
<th class="tg-c3ow">
Variância
</th>
</tr>
</thead>
<tbody>
<tr>
<td class="tg-c3ow">
<span class="math inline">\(X_1\)</span>
</td>
<td class="tg-c3ow">
<span class="math inline">\(\sigma_{11}\)</span>
</td>
<td class="tg-c3ow">
<span class="math inline">\(Y_1\)</span>
</td>
<td class="tg-c3ow">
<span class="math inline">\(\lambda_1\)</span>
</td>
</tr>
<tr>
<td class="tg-c3ow">
<span class="math inline">\(X_2\)</span>
</td>
<td class="tg-c3ow">
<span class="math inline">\(\sigma_{22}\)</span>
</td>
<td class="tg-c3ow">
<span class="math inline">\(Y_2\)</span>
</td>
<td class="tg-c3ow">
<span class="math inline">\(\lambda_2\)</span>
</td>
</tr>
<tr>
<td class="tg-c3ow">
<span class="math inline">\(\vdots\)</span>
</td>
<td class="tg-c3ow">
<span class="math inline">\(\vdots\)</span>
</td>
<td class="tg-c3ow">
<span class="math inline">\(\vdots\)</span>
</td>
<td class="tg-c3ow">
<span class="math inline">\(\vdots\)</span>
</td>
</tr>
<tr>
<td class="tg-c3ow">
<span class="math inline">\(X_p\)</span>
</td>
<td class="tg-c3ow">
<span class="math inline">\(\sigma_{pp}\)</span>
</td>
<td class="tg-c3ow">
<span class="math inline">\(Y_p\)</span>
</td>
<td class="tg-c3ow">
<span class="math inline">\(\lambda_p\)</span>
</td>
</tr>
<tr>
<td class="tg-c3ow">
Total
</td>
<td class="tg-c3ow">
<span class="math inline">\(\sigma_T^2\)</span> = <span class="math inline">\(\displaystyle{\sum_{j=1}^p \sigma_{jj}} = \rm{tr}(\boldsymbol{\Sigma})\)</span>
</td>
<td class="tg-c3ow">
Total
</td>
<td class="tg-c3ow">
<span class="math inline">\(\lambda_T = \displaystyle{\sum_{j=1}^p \lambda_j} = \rm{tr}(\boldsymbol{\Lambda})\)</span>
</td>
</tr>
</tbody>
</table>
<div class="fragment">
<p><span class="math display">\[\rm{tr}(\boldsymbol{\Sigma}) = \rm{tr}(\boldsymbol{O} \boldsymbol{\Lambda} \boldsymbol{O}^t) = \rm{tr}(\boldsymbol{\Lambda} \boldsymbol{O}^t \boldsymbol{O}) = \rm{tr}(\boldsymbol{\Lambda} \boldsymbol{I}) = \rm{tr}(\boldsymbol{\Lambda})\]</span></p>
</div>
<div class="fragment">
<p><span class="math display">\[\sigma_T^2 = \lambda_T\]</span></p>
</div>
</section>
<section id="variabilidade-explicada-1" class="slide level2">
<h2>Variabilidade explicada</h2>
<ul>
<li>Pode-se então concluir que a <strong>j-ésima componente explica</strong></li>
</ul>
<p><span class="math display">\[\displaystyle{\frac{\textrm{Var}[Y_j]}{\textrm{Variância Total de X}}} = \displaystyle{\frac{\lambda_j}{\textrm{tr}(\boldsymbol{\Sigma})}} =
\displaystyle{\frac{\lambda_j}{\displaystyle{\sum_{i=1}^p \lambda_i}}}\]</span></p>
<p>da variação total original, e ainda, que as <strong><span class="math inline">\(r\)</span> primeiras</strong> componentes explicam</p>
<p><span class="math display">\[\displaystyle{\frac{ \displaystyle \sum_{j=1}^r \textrm{Var}[Y_j]}{\textrm{Variância Total de X}}} = \displaystyle{\frac{\displaystyle \sum_{j=1}^r \lambda_j}{\textrm{tr}(\boldsymbol{\Sigma})}} =
\displaystyle{\frac{\displaystyle \sum_{j=1}^r \lambda_j}{\displaystyle{\sum_{i=1}^p \lambda_i}}}\]</span></p>
<p>da variação total.</p>
</section>
<section id="variabilidade-explicada-2" class="slide level2">
<h2>Variabilidade explicada</h2>
<ul>
<li>Busca-se analisar um conjunto menor de variáveis sem perder muita informação sobre a estrutura de variabilidade original</li>
</ul>
<div class="fragment">
<ul>
<li>Aproximação de <span class="math inline">\(\boldsymbol{\Sigma}\)</span>: Analisando as <span class="math inline">\(r\)</span> primeiras componentes principais</li>
</ul>
<p><span class="math display">\[\boldsymbol{\Sigma} \approx \displaystyle \sum_{i=1}^r \lambda_i \boldsymbol{e}_i \boldsymbol{e}_i^t\]</span></p>
</div>
<div class="fragment">
<ul>
<li>Cada parcela da soma envolve uma matriz de dimensão <span class="math inline">\(p \times p\)</span> correspondente apenas à informação da <span class="math inline">\(j\)</span>-ésima componente principal</li>
</ul>
</div>
</section>
<section id="correlação-com-as-variáveis-originais" class="slide level2">
<h2>Correlação com as variáveis originais</h2>
<ul>
<li>Os coeficientes de correlação entre a <span class="math inline">\(j\)</span>-ésima variável e a <span class="math inline">\(i\)</span>-ésima componente principal é dada por:</li>
</ul>
<p><span class="math display">\[\rho_{Y_i,X_j} = \displaystyle{\frac{e_{ij} \sqrt{\lambda_i}}{\sqrt{\sigma_{jj}}}}\]</span></p>
<div class="fragment">
<ul>
<li>As correlações medem unicamente a importância de uma variável individual sem considerar a influência das demais. Não medem a importância de <span class="math inline">\(X_i\)</span> na presença de outras variáveis.</li>
</ul>
</div>
<div class="fragment">
<ul>
<li>Os coeficientes (<strong>cargas</strong>) dos componentes (<span class="math inline">\(e_{ij}\)</span>), seus sinais e magnitudes, permitem interpretar os componentes e avaliar a importância das variáveis em sua constituição.</li>
</ul>
</div>
</section>
<section id="estimação-das-componentes-principais" class="slide level2">
<h2>Estimação das Componentes Principais</h2>
<ul>
<li>Em geral, <span class="math inline">\(\boldsymbol{\Sigma}\)</span> é estimada por <span class="math inline">\(\boldsymbol{S}\)</span></li>
</ul>
<p><span class="math display">\[\boldsymbol{S} = \left[ \begin{array}{cccc} s_{11} &amp; s_{12} &amp; \cdots &amp; s_{1p}
\\ s_{21} &amp; s_{22} &amp; \cdots &amp; s_{2p}
\\ \vdots &amp; \vdots &amp; \ddots &amp; \vdots
\\ s_{p1} &amp; s_{p2} &amp; \cdots &amp; s_{pp} \end{array} \right]\]</span></p>
<div class="fragment">
<ul>
<li>Autovalores de <span class="math inline">\(\boldsymbol{S}\)</span>: <span class="math inline">\(\hat{\lambda}_1, \hat{\lambda}_2, \cdots, \hat{\lambda}_p\)</span></li>
</ul>
</div>
<div class="fragment">
<ul>
<li>Autovetores de <span class="math inline">\(\boldsymbol{S}\)</span>: <span class="math inline">\(\hat{\boldsymbol{e}}_1, \hat{\boldsymbol{e}}_2, \cdots, \hat{\boldsymbol{e}}_p\)</span></li>
</ul>
</div>
</section>
<section id="estimação-das-componentes-principais-1" class="slide level2">
<h2>Estimação das Componentes Principais</h2>
<ul>
<li>Estimação da <span class="math inline">\(j\)</span>-ésima componente principal de <span class="math inline">\(\boldsymbol{S}\)</span>:</li>
</ul>
<p><span class="math display">\[\hat{Y}_j = {\hat{\boldsymbol{e}}_j^t}\mathbf{x} =  \hat{e}_{j1}X_1 + \hat{e}_{j2}X_2 + \cdots + \hat{e}_{jp}X_p, \,\,\,\,\,\, j = 1, 2, \cdots, p\]</span></p>
<div class="fragment">
<ul>
<li>Componentes principais amostrais - Propriedades
<ul>
<li>Variância: <span class="math inline">\(\text{Var}(\hat{Y}_j) = \hat{\lambda}_j\)</span></li>
<li>Covariância entre as componentes: <span class="math inline">\(\text{Cov}(\hat{Y}_j, \hat{Y}_k) = 0, \,\,\, j \neq k\)</span></li>
<li>Variância total estimada explicada pela componente: <span class="math display">\[\dfrac{\text{Var}(\hat{Y}_j)}{\text{Variância total estimada de } \mathbf{x}} = \dfrac{\hat{\lambda}_j}{\text{tr}(\boldsymbol{S})} =  \dfrac{\hat{\lambda}_j}{\sum \limits_{i=1}^p \hat{\lambda}_i}\]</span></li>
</ul></li>
</ul>
</div>
</section>
<section id="estimação-das-componentes-principais-2" class="slide level2">
<h2>Estimação das Componentes Principais</h2>
<ul>
<li>Correlação estimada entre componente e variável: <span class="math display">\[r_{\hat{Y}_j,\hat{X}_k} = \displaystyle{\frac{\hat{e}_{jk} \sqrt{\hat{\lambda}_j}}{\sqrt{\sigma_{kk}}}}\]</span></li>
</ul>
<div class="fragment">
<ul>
<li>Decomposição espectral de <span class="math inline">\(\boldsymbol{S}\)</span>:</li>
</ul>
<p><span class="math display">\[\boldsymbol{S} = \displaystyle \sum_{j=1}^p \hat{\lambda}_j  \hat{\boldsymbol{e}}_j  \hat{\boldsymbol{e}}_j^t\]</span></p>
</div>
</section>
<section id="estimação-das-componentes-principais-3" class="slide level2">
<h2>Estimação das Componentes Principais</h2>
<ul>
<li>Aproximação de <span class="math inline">\(\boldsymbol{S}\)</span> pelas <span class="math inline">\(r\)</span> primeiras componentes</li>
</ul>
<p><span class="math display">\[\boldsymbol{S} \approx \displaystyle \sum_{j=1}^r \hat{\lambda}_j \hat{\boldsymbol{e}}_j  \hat{\boldsymbol{e}}_j^t\]</span></p>
<div class="fragment">
<ul>
<li>Escores das componentes
<ul>
<li>Valor das componentes para cada elemento amostral</li>
<li>Na prática, o uso das componentes relevantes se dá através dos escores</li>
</ul></li>
</ul>
</div>
</section>
<section id="exemplo-mingoti2007" class="slide level2">
<h2>Exemplo: (Mingoti,2007)</h2>
<p style="text-align: center; color: black; font-size: 34px;">
12 empresas, 3 variáveis: ganho bruto (<span class="math inline">\(X_1\)</span>), ganho líquido (<span class="math inline">\(X_2\)</span>) e patrimônio acumulado (<span class="math inline">\(X_3\)</span>)
</p>
<style type="text/css">
.tg  {border:none;border-collapse:collapse;border-color:#ccc;border-spacing:0;margin:0px auto;}
.tg td{background-color:#fff;border-color:#ccc;border-style:solid;border-width:0px;color:#333;
  font-family:Arial, sans-serif;font-size:30px;overflow:hidden;padding:10px 5px;word-break:normal;}
.tg th{background-color:#f0f0f0;border-color:#ccc;border-style:solid;border-width:0px;color:#333;
  font-family:Arial, sans-serif;font-size:30px;font-weight:normal;overflow:hidden;padding:10px 5px;word-break:normal;}
.tg .tg-c3ow{border-color:white;text-align:center;vertical-align:top}
</style>
<table class="tg">
<thead>
<tr>
<th class="tg-c3ow">
Empresa
</th>
<th class="tg-c3ow">
Ganho bruto <span class="math inline">\((X_1)\)</span>
</th>
<th class="tg-c3ow">
Ganho líquido <span class="math inline">\((X_2)\)</span>
</th>
<th class="tg-c3ow">
Patrimônio <span class="math inline">\((X_3)\)</span>
</th>
</tr>
</thead>
<tbody>
<tr>
<td class="tg-c3ow">
E1
</td>
<td class="tg-c3ow">
9893
</td>
<td class="tg-c3ow">
564
</td>
<td class="tg-c3ow">
17689
</td>
</tr>
<tr>
<td class="tg-c3ow">
E2
</td>
<td class="tg-c3ow">
8776
</td>
<td class="tg-c3ow">
389
</td>
<td class="tg-c3ow">
17359
</td>
</tr>
<tr>
<td class="tg-c3ow">
E3
</td>
<td class="tg-c3ow">
13572
</td>
<td class="tg-c3ow">
1103
</td>
<td class="tg-c3ow">
18597
</td>
</tr>
<tr>
<td class="tg-c3ow">
E4
</td>
<td class="tg-c3ow">
6455
</td>
<td class="tg-c3ow">
743
</td>
<td class="tg-c3ow">
8745
</td>
</tr>
<tr>
<td class="tg-c3ow">
E5
</td>
<td class="tg-c3ow">
5129
</td>
<td class="tg-c3ow">
203
</td>
<td class="tg-c3ow">
14397
</td>
</tr>
<tr>
<td class="tg-c3ow">
E6
</td>
<td class="tg-c3ow">
5432
</td>
<td class="tg-c3ow">
215
</td>
<td class="tg-c3ow">
3467
</td>
</tr>
<tr>
<td class="tg-c3ow">
E7
</td>
<td class="tg-c3ow">
3807
</td>
<td class="tg-c3ow">
385
</td>
<td class="tg-c3ow">
4679
</td>
</tr>
<tr>
<td class="tg-c3ow">
E8
</td>
<td class="tg-c3ow">
3423
</td>
<td class="tg-c3ow">
187
</td>
<td class="tg-c3ow">
6754
</td>
</tr>
<tr>
<td class="tg-c3ow">
E9
</td>
<td class="tg-c3ow">
3708
</td>
<td class="tg-c3ow">
127
</td>
<td class="tg-c3ow">
2275
</td>
</tr>
<tr>
<td class="tg-c3ow">
E10
</td>
<td class="tg-c3ow">
3294
</td>
<td class="tg-c3ow">
297
</td>
<td class="tg-c3ow">
6754
</td>
</tr>
<tr>
<td class="tg-c3ow">
E11
</td>
<td class="tg-c3ow">
5433
</td>
<td class="tg-c3ow">
432
</td>
<td class="tg-c3ow">
5589
</td>
</tr>
<tr>
<td class="tg-c3ow">
E12
</td>
<td class="tg-c3ow">
6287
</td>
<td class="tg-c3ow">
451
</td>
<td class="tg-c3ow">
8972
</td>
</tr>
</tbody>
</table>
</section>
<section id="primeiro-exemplo-mingoti2007" class="slide level2">
<h2>Primeiro Exemplo: (Mingoti,2007)</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a></a>load <span class="ot">&lt;-</span> <span class="cf">function</span>(pkg){</span>
<span id="cb1-2"><a></a>  new.pkg <span class="ot">&lt;-</span> pkg[<span class="sc">!</span>(pkg <span class="sc">%in%</span> <span class="fu">installed.packages</span>()[, <span class="st">"Package"</span>])]</span>
<span id="cb1-3"><a></a>  <span class="cf">if</span> (<span class="fu">length</span>(new.pkg))</span>
<span id="cb1-4"><a></a>    <span class="fu">install.packages</span>(new.pkg, <span class="at">dependencies =</span> <span class="cn">TRUE</span>)</span>
<span id="cb1-5"><a></a>  <span class="fu">sapply</span>(pkg, require, <span class="at">character.only =</span> <span class="cn">TRUE</span>)</span>
<span id="cb1-6"><a></a>} </span>
<span id="cb1-7"><a></a></span>
<span id="cb1-8"><a></a><span class="do">## Pacotes utilizados nessa análise</span></span>
<span id="cb1-9"><a></a></span>
<span id="cb1-10"><a></a>packages <span class="ot">=</span> <span class="fu">c</span>(<span class="st">"tidyverse"</span>, <span class="st">"factoextra"</span>, <span class="st">"psych"</span>, <span class="st">"gridExtra"</span>)</span>
<span id="cb1-11"><a></a><span class="fu">load</span>(packages)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> tidyverse factoextra      psych  gridExtra 
      TRUE       TRUE       TRUE       TRUE </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a></a>dados <span class="ot">&lt;-</span> <span class="fu">read.table</span>(<span class="st">"https://raw.githubusercontent.com/tiagomartin/est014/refs/heads/master/dados/empresas.txt"</span>, <span class="at">row.names =</span> <span class="dv">1</span>, <span class="at">header =</span> <span class="cn">TRUE</span>) </span>
<span id="cb3-2"><a></a>dados <span class="sc">%&gt;%</span> </span>
<span id="cb3-3"><a></a>  <span class="fu">str</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   12 obs. of  3 variables:
 $ Granho_Bruto : int  9893 8776 13572 6455 5129 5432 3807 3423 3708 3294 ...
 $ Ganho_Liquido: int  564 389 1103 743 203 215 385 187 127 297 ...
 $ Patrimonio   : int  17689 17359 18597 8745 14397 3467 4679 6754 2275 6754 ...</code></pre>
</div>
</div>
</section>
<section id="primeiro-exemplo-mingoti2007-1" class="slide level2">
<h2>Primeiro Exemplo: (Mingoti,2007)</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a></a>x_barra <span class="ot">=</span> dados <span class="sc">%&gt;%</span> </span>
<span id="cb5-2"><a></a>  <span class="fu">colMeans</span>()</span>
<span id="cb5-3"><a></a></span>
<span id="cb5-4"><a></a>x_barra</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> Granho_Bruto Ganho_Liquido    Patrimonio 
    6267.4167      424.6667     9606.4167 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a></a>S <span class="ot">=</span> dados <span class="sc">%&gt;%</span> </span>
<span id="cb7-2"><a></a>  <span class="fu">var</span>()</span>
<span id="cb7-3"><a></a></span>
<span id="cb7-4"><a></a>S</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>              Granho_Bruto Ganho_Liquido Patrimonio
Granho_Bruto     9550608.6     706121.06 14978232.5
Ganho_Liquido     706121.1      76269.52   933915.1
Patrimonio      14978232.5     933915.06 34408113.0</code></pre>
</div>
</div>
</section>
<section id="primeiro-exemplo-mingoti2007-2" class="slide level2">
<h2>Primeiro Exemplo: (Mingoti,2007)</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a></a>dados <span class="sc">%&gt;%</span> </span>
<span id="cb9-2"><a></a>  <span class="fu">boxplot</span>() </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>

</div>
<img data-src="comp_princ_files/figure-revealjs/unnamed-chunk-4-1.png" width="960" class="r-stretch"></section>
<section id="primeiro-exemplo-mingoti2007-3" class="slide level2">
<h2>Primeiro Exemplo: (Mingoti,2007)</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a></a><span class="do">## Analise de Componentes Principais utilizando a matriz de covariancias (Nao aconselhavel, neste caso)</span></span>
<span id="cb10-2"><a></a>acp_S <span class="ot">=</span> <span class="fu">prcomp</span>(dados)</span>
<span id="cb10-3"><a></a></span>
<span id="cb10-4"><a></a><span class="do">## Proporcao da variacao explicada</span></span>
<span id="cb10-5"><a></a><span class="fu">summary</span>(acp_S)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Importance of components:
                             PC1       PC2       PC3
Standard deviation     6440.0615 1.594e+03 145.23266
Proportion of Variance    0.9418 5.767e-02   0.00048
Cumulative Proportion     0.9418 9.995e-01   1.00000</code></pre>
</div>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a></a><span class="do">## Loadings (cargas)</span></span>
<span id="cb12-2"><a></a>acp_S<span class="sc">$</span>rotation</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                      PC1         PC2         PC3
Granho_Bruto  -0.42509725 -0.89970680 -0.09909593
Ganho_Liquido -0.02766083 -0.09651661  0.99494694
Patrimonio    -0.90472493  0.42569029  0.01614231</code></pre>
</div>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a></a><span class="do">## Opcional: trocar sinal da primeira componente e escores</span></span>
<span id="cb14-2"><a></a>acp_S<span class="sc">$</span>rotation <span class="ot">=</span> <span class="sc">-</span>acp_S<span class="sc">$</span>rotation</span>
<span id="cb14-3"><a></a>acp_S<span class="sc">$</span>x <span class="ot">=</span> <span class="sc">-</span>acp_S<span class="sc">$</span>x</span>
<span id="cb14-4"><a></a></span>
<span id="cb14-5"><a></a><span class="do">## Loadings (cargas)</span></span>
<span id="cb14-6"><a></a>acp_S<span class="sc">$</span>rotation</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                     PC1         PC2         PC3
Granho_Bruto  0.42509725  0.89970680  0.09909593
Ganho_Liquido 0.02766083  0.09651661 -0.99494694
Patrimonio    0.90472493 -0.42569029 -0.01614231</code></pre>
</div>
</div>
</section>
<section id="primeiro-exemplo-mingoti2007-4" class="slide level2">
<h2>Primeiro Exemplo: (Mingoti,2007)</h2>
<p><span class="math display">\[Y_1 = 0,425 \times \text{GB} + 0,028 \times \text{GL} + 0,905 \times \text{PA} \Longrightarrow
94,18\% \text{ da informação total de } \mathbf{x}\]</span></p>
<div class="fragment">
<p style="text-align: center; color: red; font-size: 46px;">
<strong>Qual a variável mais importante para <span class="math inline">\(Y_1\)</span>?</strong>
</p>
<div class="fragment fade-in">
<p style="text-align: center; color: black; font-size: 46px;">
<strong>Patrimônio</strong>
</p>
</div>
<div class="fragment fade-up">
<div class="columns">
<div class="column" style="width:60%;">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="../..\images/CP/empresas_bp.png" class="quarto-figure quarto-figure-center"></p>
</figure>
</div>
</div><div class="column" style="width:40%;">
<p style="text-align: center; color: red; font-size: 100px;">
<span style="font-size:150px;">🤔</span><strong>Será?</strong>
</p>
</div></div>
</div>
</div>
</section>
<section id="componentes-principais-variáveis-padronizadas" class="slide level2">
<h2>Componentes Principais: variáveis padronizadas</h2>
<ul>
<li>Padronização do vetor aleatório <span class="math inline">\(\mathbf{x}\)</span>:</li>
</ul>
<p><span class="math display">\[\boldsymbol{z} = \boldsymbol{D}^{-1}(\mathbf{x} - \boldsymbol{\mu})\]</span></p>
<div class="fragment">
<ul>
<li><span class="math inline">\(\boldsymbol{D}\)</span>: matriz diagonal de desvios-padrão</li>
</ul>
</div>
<div class="fragment">
<ul>
<li>Variável padronizada: <span class="math inline">\(Z_i = \dfrac{X_i - \mu_i}{\sqrt{\sigma_{ii}}}\)</span></li>
</ul>
</div>
<div class="fragment">
<ul>
<li>Matriz de covariâncias de <span class="math inline">\(\boldsymbol{z}\)</span></li>
</ul>
<p><span class="math display">\[\text{Cov}(\boldsymbol{z}) = \boldsymbol{D}^{-1}\boldsymbol{\Sigma}  \boldsymbol{D}^{-1} = \boldsymbol{P} = \text{Cor}(\mathbf{x})\]</span></p>
</div>
<div class="fragment">
<ul>
<li>Componentes principais de <span class="math inline">\(\boldsymbol{z}\)</span>: obtidas dos autovalores e autovetores de <span class="math inline">\(\boldsymbol{P}\)</span></li>
</ul>
</div>
</section>
<section id="componentes-principais-variáveis-padronizadas-1" class="slide level2">
<h2>Componentes Principais: variáveis padronizadas</h2>
<ul>
<li>A <span class="math inline">\(j\)</span>-ésima componente principal da matriz <span class="math inline">\(\boldsymbol{P}\)</span>:</li>
</ul>
<p><span class="math display">\[Y_j = \boldsymbol{e}_j^t \boldsymbol{z} =  \boldsymbol{e}_j^t \boldsymbol{D}^{-1}(\mathbf{x} - \boldsymbol{\mu}) = {e}_{j1}Z_1 + {e}_{j2}Z_2 + \cdots + {e}_{jp}Z_p\]</span></p>
<p>sendo <span class="math inline">\(\boldsymbol{e}_j\)</span>, o <span class="math inline">\(j\)</span>-ésimo autovetor da matriz <span class="math inline">\(\boldsymbol{P}\)</span>, <span class="math inline">\(j = 1, \cdots p\)</span>.</p>
<div class="fragment">
<ul>
<li>Variância total de <span class="math inline">\(\boldsymbol{P}\)</span></li>
</ul>
<p><span class="math display">\[\sum \limits_{j=1}^p \text{Var}(Y_j) = \sum \limits_{j=1}^p \text{Var}(Z_j) = p\]</span></p>
</div>
</section>
<section id="componentes-principais-variáveis-padronizadas-2" class="slide level2">
<h2>Componentes Principais: variáveis padronizadas</h2>
<ul>
<li>Proporção da variância populacional padronizada devido à <span class="math inline">\(j\)</span>-ésima componente</li>
</ul>
<p><span class="math display">\[\dfrac{\text{Var}({Y}_j)}{\text{Variância total de } \boldsymbol{z}} = \dfrac{{\lambda}_j}{\text{tr} (\boldsymbol{P})} =  \dfrac{{\lambda}_j}{p}\]</span></p>
<div class="fragment">
<ul>
<li>Correlação entre componente <span class="math inline">\(Y_j\)</span> e a variável padronizada <span class="math inline">\(Z_k\)</span>:</li>
</ul>
<p><span class="math display">\[\rho_{Y_j,Z_k} = e_{jk} \sqrt{\lambda_j}\]</span></p>
</div>
</section>
<section id="observações" class="slide level2">
<h2>Observações</h2>
<ul>
<li>As componentes principais <strong>não são invariantes à mudanças de escala</strong>. Os resultados são <strong>diferentes</strong> quando se faz a análise utilizando a matriz de covariâncias e a matriz de correlações.</li>
</ul>
<div class="fragment">
<ul>
<li><strong>As componentes obtidas a partir da matriz de covariâncias são influenciadas pelas variáveis de maior variância</strong>. A <strong>matriz de correlações</strong>, em geral, é a melhor opção quando as <strong>variâncias são muito heterogêneas</strong>.</li>
</ul>
</div>
<div class="fragment">
<ul>
<li>Um valor <strong>pequeno incomum</strong> para o <strong>último autovalor</strong> da matriz de covariâncias (ou correlação) amostral pode indicar uma <strong>dependência linear não detectada</strong> no conjunto de dados.</li>
</ul>
</div>
<div class="fragment">
<ul>
<li>Valores grandes de autovalores (e correspondentes autovetores) são importantes em uma análise.</li>
</ul>
</div>
</section>
<section id="quantas-componentes-devem-ser-retidas" class="slide level2">
<h2>Quantas componentes devem ser retidas?</h2>
<ul>
<li><strong>Critério de Kaiser:</strong> Trata-se de uma regra prática (heurística) para decidir quantas componentes principais manter em uma PCA extraída através da matriz de correlações. Ele diz:</li>
</ul>
<blockquote>
<p>Retenha apenas as componentes associadas a um autovalor maior que 1.</p>
</blockquote>
<ul>
<li><span class="math inline">\(\lambda = 1\)</span> → a componente explica tanta variabilidade quanto 1 variável original</li>
<li><span class="math inline">\(\lambda &gt; 1\)</span> → explica mais variabilidade do que qualquer variável isolada</li>
<li><span class="math inline">\(\lambda &lt; 1\)</span> → explica menos variabilidade do que uma única variável → então não “vale a pena”</li>
</ul>
</section>
<section id="quantas-componentes-devem-ser-retidas-1" class="slide level2">
<h2>Quantas componentes devem ser retidas?</h2>
<ul>
<li><strong>Média dos autovalores:</strong> É um critério alternativo quando a PCA é feita sobre <strong>matriz de covariâncias</strong>.</li>
</ul>
<blockquote>
<p>Se PCA foi feita na matriz de covariâncias, retenha PCs com autovalores maiores que a média dos autovalores.</p>
</blockquote>
<p>Então, se uma componente tem autovalor:</p>
<p><span class="math display">\[\lambda_k &gt; \dfrac{\sum \limits_{j=1}^p \lambda_j}{p}\]</span></p>
<p>ela retém mais informação do que a variância média por dimensão do espaço original.</p>
</section>
<section id="quantas-componentes-devem-ser-retidas-2" class="slide level2">
<h2>Quantas componentes devem ser retidas?</h2>
<ul>
<li><strong>Screeplot:</strong> É um gráfico que coloca, no eixo X, o número da componente principal e, no eixo Y, o autovalor (ou a variância explicada).</li>
</ul>
<blockquote>
<p>O ponto onde a curva deixa de cair abruptamente e começa a “horizontalizar” é onde você para de manter componentes.</p>
</blockquote>
<ul>
<li>A ideia é identificar o “cotovelo” da curva.
<ul>
<li>antes do cotovelo: cada componente adiciona bastante variância</li>
<li>depois do cotovelo: os autovalores ficam “quase uma linha reta” → só ruído</li>
</ul></li>
</ul>
</section>
<section id="quantas-componentes-devem-ser-retidas-3" class="slide level2">
<h2>Quantas componentes devem ser retidas?</h2>

<img data-src="comp_princ_files/figure-revealjs/unnamed-chunk-6-1.png" width="960" class="r-stretch"></section>
<section id="quantas-componentes-devem-ser-retidas-4" class="slide level2">
<h2>Quantas componentes devem ser retidas?</h2>
<ul>
<li>Reter o número de componentes principais que acumulem pelo menos certa porcentagem da variabilidade total dos dados, digamos 70%.</li>
</ul>

<img data-src="comp_princ_files/figure-revealjs/unnamed-chunk-7-1.png" width="960" class="r-stretch"></section>
<section id="quantas-componentes-devem-ser-retidas-5" class="slide level2">
<h2>Quantas componentes devem ser retidas?</h2>
<ul>
<li><strong>Parallel Analysis (Horn, 1965):</strong> É o método moderno mais recomendado para decidir quantos componentes reter em PCA.</li>
</ul>
<blockquote>
<p>Compare seus autovalores reais com autovalores esperados ao acaso.</p>
</blockquote>
</section>
<section id="quantas-componentes-devem-ser-retidas-6" class="slide level2">
<h2>Quantas componentes devem ser retidas?</h2>
<ul>
<li>O procedimento envolve:
<ul>
<li>Calcular os autovalores dos dados originais.</li>
<li>Gerar dados aleatórios com a mesma estrutura dos dados originais.</li>
<li>Calcular autovalores para os dados aleatórios, repetindo o processo muitas vezes para obter uma distribuição amostral.</li>
<li>Comparar os autovalores reais com os autovalores médios ou percentis (como o 95º) dos dados simulados.</li>
<li>Reter os componentes cujos autovalores reais são maiores do que os autovalores aleatórios correspondentes.</li>
</ul></li>
</ul>
</section>
<section id="quantas-componentes-devem-ser-retidas-7" class="slide level2">
<h2>Quantas componentes devem ser retidas?</h2>
<div class="cell">

<div class="cell-output cell-output-stdout">
<pre><code>Parallel analysis suggests that the number of factors =  NA  and the number of components =  1 </code></pre>
</div>
</div>
<img data-src="comp_princ_files/figure-revealjs/unnamed-chunk-8-1.png" width="960" class="r-stretch"></section>
<section id="quantas-componentes-devem-ser-retidas-8" class="slide level2">
<h2>Quantas componentes devem ser retidas?</h2>
<ul>
<li><strong>Interpretação desse gráfico</strong>
<ul>
<li>linha azul = autovalores reais dos seus dados</li>
<li>linhas vermelha / pontilhada = autovalores esperados pelo acaso (parallel analysis)</li>
</ul></li>
</ul>
<div class="fragment">
<ul>
<li><strong>Regra:</strong> retenha apenas os componentes cuja linha azul está acima da linha vermelha.
<ul>
<li>Parallel Analysis (Horn) está dizendo: retenha 1 componente principal.</li>
</ul></li>
</ul>
</div>
</section>
<section id="interpretação-das-componentes-principais" class="slide level2">
<h2>Interpretação das componentes principais</h2>
<ul>
<li>Em geral, quando existe uma <strong>alta correlação positiva</strong> entre todas as variáveis, os <strong>sinais associados às variáveis coincidem</strong> na primeira componente principal.</li>
</ul>
<div class="fragment">
<ul>
<li>Neste caso, a primeira componente principal pode ser interpretada como um <strong>índice global</strong>, calculado como uma média ponderada de todas as variáveis.</li>
</ul>
</div>
<div class="fragment">
<ul>
<li>O restante das componentes, normalmente possuem <strong>pesos negativos e positivos</strong> e são interpretadas como um <strong>contraste entre grupos de variáveis</strong>.</li>
</ul>
</div>
</section>
<section id="voltando-ao-exemplo" class="slide level2">
<h2>Voltando ao Exemplo</h2>
<p style="text-align: center; color: black; font-size: 34px;">
12 empresas, 3 variáveis: ganho bruto (<span class="math inline">\(X_1\)</span>), ganho líquido (<span class="math inline">\(X_2\)</span>) e patrimônio acumulado (<span class="math inline">\(X_3\)</span>)
</p>
<style type="text/css">
.tg  {border:none;border-collapse:collapse;border-color:#ccc;border-spacing:0;margin:0px auto;}
.tg td{background-color:#fff;border-color:#ccc;border-style:solid;border-width:0px;color:#333;
  font-family:Arial, sans-serif;font-size:30px;overflow:hidden;padding:10px 5px;word-break:normal;}
.tg th{background-color:#f0f0f0;border-color:#ccc;border-style:solid;border-width:0px;color:#333;
  font-family:Arial, sans-serif;font-size:30px;font-weight:normal;overflow:hidden;padding:10px 5px;word-break:normal;}
.tg .tg-c3ow{border-color:white;text-align:center;vertical-align:top}
</style>
<table class="tg">
<thead>
<tr>
<th class="tg-c3ow">
Empresa
</th>
<th class="tg-c3ow">
Ganho bruto <span class="math inline">\((X_1)\)</span>
</th>
<th class="tg-c3ow">
Ganho líquido <span class="math inline">\((X_2)\)</span>
</th>
<th class="tg-c3ow">
Patrimônio <span class="math inline">\((X_3)\)</span>
</th>
</tr>
</thead>
<tbody>
<tr>
<td class="tg-c3ow">
E1
</td>
<td class="tg-c3ow">
9893
</td>
<td class="tg-c3ow">
564
</td>
<td class="tg-c3ow">
17689
</td>
</tr>
<tr>
<td class="tg-c3ow">
E2
</td>
<td class="tg-c3ow">
8776
</td>
<td class="tg-c3ow">
389
</td>
<td class="tg-c3ow">
17359
</td>
</tr>
<tr>
<td class="tg-c3ow">
E3
</td>
<td class="tg-c3ow">
13572
</td>
<td class="tg-c3ow">
1103
</td>
<td class="tg-c3ow">
18597
</td>
</tr>
<tr>
<td class="tg-c3ow">
E4
</td>
<td class="tg-c3ow">
6455
</td>
<td class="tg-c3ow">
743
</td>
<td class="tg-c3ow">
8745
</td>
</tr>
<tr>
<td class="tg-c3ow">
E5
</td>
<td class="tg-c3ow">
5129
</td>
<td class="tg-c3ow">
203
</td>
<td class="tg-c3ow">
14397
</td>
</tr>
<tr>
<td class="tg-c3ow">
E6
</td>
<td class="tg-c3ow">
5432
</td>
<td class="tg-c3ow">
215
</td>
<td class="tg-c3ow">
3467
</td>
</tr>
<tr>
<td class="tg-c3ow">
E7
</td>
<td class="tg-c3ow">
3807
</td>
<td class="tg-c3ow">
385
</td>
<td class="tg-c3ow">
4679
</td>
</tr>
<tr>
<td class="tg-c3ow">
E8
</td>
<td class="tg-c3ow">
3423
</td>
<td class="tg-c3ow">
187
</td>
<td class="tg-c3ow">
6754
</td>
</tr>
<tr>
<td class="tg-c3ow">
E9
</td>
<td class="tg-c3ow">
3708
</td>
<td class="tg-c3ow">
127
</td>
<td class="tg-c3ow">
2275
</td>
</tr>
<tr>
<td class="tg-c3ow">
E10
</td>
<td class="tg-c3ow">
3294
</td>
<td class="tg-c3ow">
297
</td>
<td class="tg-c3ow">
6754
</td>
</tr>
<tr>
<td class="tg-c3ow">
E11
</td>
<td class="tg-c3ow">
5433
</td>
<td class="tg-c3ow">
432
</td>
<td class="tg-c3ow">
5589
</td>
</tr>
<tr>
<td class="tg-c3ow">
E12
</td>
<td class="tg-c3ow">
6287
</td>
<td class="tg-c3ow">
451
</td>
<td class="tg-c3ow">
8972
</td>
</tr>
</tbody>
</table>
</section>
<section id="voltando-ao-exemplo-1" class="slide level2">
<h2>Voltando ao Exemplo</h2>

<img data-src="../..\images/CP/empresas_bp.png" class="quarto-figure quarto-figure-center r-stretch"></section>
<section id="voltando-ao-exemplo-2" class="slide level2">
<h2>Voltando ao Exemplo</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a></a>dados <span class="sc">%&gt;%</span> </span>
<span id="cb17-2"><a></a>  <span class="fu">scale</span>(<span class="at">center=</span><span class="cn">TRUE</span>, <span class="at">scale=</span><span class="cn">TRUE</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    Granho_Bruto Ganho_Liquido Patrimonio
E1   1.173173832    0.50452133  1.3779065
E2   0.811732638   -0.12914781  1.3216486
E3   2.363632341    2.45622228  1.5327010
E4   0.060698607    1.15267434 -0.1468530
E5  -0.368371244   -0.80264757  0.8166914
E6  -0.270325871   -0.75919598 -1.0466384
E7  -0.796146767   -0.14363167 -0.8400185
E8  -0.920402290   -0.86058304 -0.4862757
E9  -0.828181394   -1.07784103 -1.2498488
E10 -0.962144379   -0.46227672 -0.4862757
E11 -0.270002289    0.02655375 -0.6848831
E12  0.006336816    0.09535212 -0.1081544
attr(,"scaled:center")
 Granho_Bruto Ganho_Liquido    Patrimonio 
    6267.4167      424.6667     9606.4167 
attr(,"scaled:scale")
 Granho_Bruto Ganho_Liquido    Patrimonio 
    3090.4059      276.1694     5865.8429 </code></pre>
</div>
</div>
</section>
<section id="voltando-ao-exemplo-3" class="slide level2">
<h2>Voltando ao Exemplo</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a></a>dados <span class="sc">%&gt;%</span> </span>
<span id="cb19-2"><a></a>  <span class="fu">scale</span>(<span class="at">center=</span><span class="cn">TRUE</span>, <span class="at">scale=</span><span class="cn">TRUE</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb19-3"><a></a>  <span class="fu">boxplot</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>

</div>
<img data-src="comp_princ_files/figure-revealjs/unnamed-chunk-10-1.png" width="960" class="r-stretch"></section>
<section id="voltando-ao-exemplo-4" class="slide level2">
<h2>Voltando ao Exemplo</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a></a><span class="do">## Analise de Componentes Principais utilizando a matriz de correlacoes (Mais aconselhavel, neste caso)</span></span>
<span id="cb20-2"><a></a>acp_R <span class="ot">=</span> <span class="fu">prcomp</span>(dados, <span class="at">scale. =</span> <span class="cn">TRUE</span>)</span>
<span id="cb20-3"><a></a></span>
<span id="cb20-4"><a></a><span class="do">## Proporcao da variacao explicada</span></span>
<span id="cb20-5"><a></a><span class="fu">summary</span>(acp_R)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Importance of components:
                          PC1    PC2     PC3
Standard deviation     1.5788 0.6508 0.28978
Proportion of Variance 0.8308 0.1412 0.02799
Cumulative Proportion  0.8308 0.9720 1.00000</code></pre>
</div>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a></a><span class="do">## Loadings (cargas)</span></span>
<span id="cb22-2"><a></a>acp_R<span class="sc">$</span>rotation</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                     PC1          PC2        PC3
Granho_Bruto  -0.6167027  0.001267206  0.7871952
Ganho_Liquido -0.5567945  0.706196936 -0.4373395
Patrimonio    -0.5564690 -0.708014324 -0.4348080</code></pre>
</div>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a></a><span class="do">## Opcional: trocar sinal da primeira componente e escores</span></span>
<span id="cb24-2"><a></a>acp_R<span class="sc">$</span>rotation <span class="ot">=</span> <span class="sc">-</span>acp_R<span class="sc">$</span>rotation</span>
<span id="cb24-3"><a></a>acp_R<span class="sc">$</span>x <span class="ot">=</span> <span class="sc">-</span>acp_R<span class="sc">$</span>x</span>
<span id="cb24-4"><a></a></span>
<span id="cb24-5"><a></a><span class="do">## Loadings (cargas)</span></span>
<span id="cb24-6"><a></a>acp_R<span class="sc">$</span>rotation</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                    PC1          PC2        PC3
Granho_Bruto  0.6167027 -0.001267206 -0.7871952
Ganho_Liquido 0.5567945 -0.706196936  0.4373395
Patrimonio    0.5564690  0.708014324  0.4348080</code></pre>
</div>
</div>
</section>
<section id="voltando-ao-exemplo-5" class="slide level2">
<h2>Voltando ao Exemplo</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a></a><span class="do">## Escores das componentes principais</span></span>
<span id="cb26-2"><a></a>Yr <span class="ot">=</span> acp_R<span class="sc">$</span>x</span>
<span id="cb26-3"><a></a>Yr <span class="sc">%&gt;%</span> <span class="fu">head</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>          PC1        PC2        PC3
E1  1.7711764  0.6177995 -0.1037449
E2  1.1641454  1.0259213 -0.1208101
E3  3.6781699 -0.6523976 -0.1200063
E4  0.5975165 -0.9180660  0.3924755
E5 -0.2196218  1.1455233  0.2940545
E6 -1.1718486 -0.2045506 -0.5743139</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a></a><span class="do">## Matriz de correlacoes entre variaveis originais e componentes principais</span></span>
<span id="cb28-2"><a></a>Ryx_R <span class="ot">=</span> <span class="fu">cor</span>(dados,Yr)</span>
<span id="cb28-3"><a></a>Ryx_R</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                    PC1           PC2        PC3
Granho_Bruto  0.9736351 -0.0008246563 -0.2281098
Ganho_Liquido 0.8790534 -0.4595699002  0.1267302
Patrimonio    0.8785396  0.4607525968  0.1259966</code></pre>
</div>
</div>
</section>
<section id="voltando-ao-exemplo-6" class="slide level2">
<h2>Voltando ao Exemplo</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a></a><span class="fu">fa.parallel</span>(dados <span class="sc">%&gt;%</span> <span class="fu">scale</span>(<span class="at">center=</span><span class="cn">TRUE</span>, <span class="at">scale=</span><span class="cn">TRUE</span>), <span class="at">fa=</span><span class="st">"pc"</span>, <span class="at">n.iter=</span><span class="dv">1000</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>

<div class="cell-output cell-output-stdout">
<pre><code>Parallel analysis suggests that the number of factors =  NA  and the number of components =  1 </code></pre>
</div>
</div>
<img data-src="comp_princ_files/figure-revealjs/unnamed-chunk-14-1.png" width="960" class="r-stretch"></section>
<section id="voltando-ao-exemplo-7" class="slide level2">
<h2>Voltando ao Exemplo</h2>
<p><span class="math display">\[Z_{GB} = \dfrac{\text{Ganho Bruto} - \overline{\text{Ganho Bruto}}}{s_{\text{Ganho Bruto}}}\]</span></p>
<p><span class="math display">\[Z_{GL} = \dfrac{\text{Ganho Líquido} - \overline{\text{Ganho Líquido}}}{s_{\text{Ganho Líquido}}}\]</span></p>
<p><span class="math display">\[Z_{PA} = \dfrac{\text{Patrimônio} - \overline{\text{Patrimônio}}}{s_{\text{Patrimônio}}}\]</span></p>
</section>
<section id="voltando-ao-exemplo-8" class="slide level2">
<h2>Voltando ao Exemplo</h2>
<p><span class="math display">\[Y_1 =  0,617 \times Z_{GB} + 0,557 \times Z_{GL} + 0,556 \times Z_{PA} \Longrightarrow
83,08\% \text{ da informação total de } \boldsymbol{z}\]</span></p>
<div class="fragment">
<ul>
<li><strong>Interpretação:</strong> É basicamente um índice de desempenho global da empresa. O coeficiente de maior grandeza numérica desta componente é relativo a ganho bruto enquanto que os demais coeficientes são aproximadamente iguais. Quanto maior os valores de ganhos brutos e líquido e patrimônio da empresa, maior será o valor numérico da componente. Além disso, todas as três variáveis possui alta correlação com essa componente, indicando serem importantes na composição da mesma.</li>
</ul>
</div>
</section>
<section id="voltando-ao-exemplo-9" class="slide level2">
<h2>Voltando ao Exemplo</h2>
<p><span class="math display">\[Y_2 =  -0,001 \times Z_{GB} - 0,706 \times Z_{GL} + 0,708 \times Z_{PA} \Longrightarrow
14,12\% \text{ da informação total de } \boldsymbol{z}\]</span></p>
<div class="fragment">
<ul>
<li><strong>Interpretação:</strong> É uma comparação entre as variáveis ganho líquido e patrimônio, sendo que essas duas variáveis possuem igual importância na composição da mesma. Valores próximos de zero dessa componente indicam empresas com um certo equilíbrio entre ganho líquido e patrimônio acumulado no período.</li>
</ul>
</div>
</section>
<section id="voltando-ao-exemplo-10" class="slide level2">
<h2>Voltando ao Exemplo</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a></a><span class="fu">fviz_pca_biplot</span>(acp_R, <span class="at">repel =</span> <span class="cn">TRUE</span>,</span>
<span id="cb32-2"><a></a>                <span class="at">col.var =</span> <span class="st">"#2E9FDF"</span>, <span class="co"># Variables color</span></span>
<span id="cb32-3"><a></a>                <span class="at">col.ind =</span> <span class="st">"#696969"</span>  <span class="co"># Individuals color</span></span>
<span id="cb32-4"><a></a>                )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>

</div>
<img data-src="comp_princ_files/figure-revealjs/unnamed-chunk-15-1.png" width="960" class="r-stretch"></section>
<section id="voltando-ao-exemplo-11" class="slide level2">
<h2>Voltando ao Exemplo</h2>
<p><strong>Interpretação do biplot</strong></p>
<ul>
<li>As setas indicam em que direção a variável aumenta. os indivíduos que estão posicionados no sentido da seta são os que têm valores maiores naquela variável.</li>
</ul>
<div class="fragment">
<ul>
<li><strong>Ângulo entre a seta (variável) e o eixo PC1:</strong> O cosseno do ângulo entre a variável e a PC é exatamente o <strong>loading</strong>.</li>
</ul>
<p><span class="math display">\[\cos(\theta_j, PC_i) = \text{loading}_{X_j, PC_i}\]</span></p>
</div>
</section>
<section id="voltando-ao-exemplo-12" class="slide level2">
<h2>Voltando ao Exemplo</h2>
<p>então:</p>
<ul>
<li>se a seta está quase colada no eixo <span class="math inline">\(PC_i\)</span>
<ul>
<li>loading próximo de +1 → variável altamente alinhada com a componente</li>
<li>é variável que define o componente principal</li>
</ul></li>
<li>se a seta faz um ângulo grande (perto de 90°) com <span class="math inline">\(PC_i\)</span>
<ul>
<li>loading <span class="math inline">\(\approx 0\)</span> → essa variável não contribui para a componente</li>
</ul></li>
<li>se a seta aponta para o lado oposto da <span class="math inline">\(PC_i\)</span> (180°)
<ul>
<li>loading <span class="math inline">\(\approx -1\)</span> → variável altamente alinhada negativamente</li>
</ul></li>
</ul>
</section>
<section id="voltando-ao-exemplo-13" class="slide level2">
<h2>Voltando ao Exemplo</h2>
<ul>
<li><strong>Observação:</strong> Quando a PCA é feita na <strong>matriz de correlações</strong>, os loadings são exatamente as correlações entre as variáveis originais e as componentes principais. Quando usamos <strong>matriz de covariâncias</strong>, os loadings refletem contribuição em variância e o cosseno do ângulo não corresponde numericamente à correlação.</li>
</ul>
</section>
<section id="voltando-ao-exemplo-14" class="slide level2">
<h2>Voltando ao Exemplo</h2>
<ul>
<li><strong>PC1 (Dim1 = 83.1%):</strong> Praticamente toda a informação relevante está aqui.</li>
</ul>
<blockquote>
<p>PC1 representa um eixo geral de nível financeiro / escala econômica. Quanto maior Patrimônio / Ganho Bruto / Ganho Líquido → mais à direita o indivíduo aparece.</p>
</blockquote>
<ul>
<li>Todas variáveis apontam para a direita, e com ângulos semelhantes → altíssima correlação entre elas</li>
</ul>
</section>
<section id="voltando-ao-exemplo-15" class="slide level2">
<h2>Voltando ao Exemplo</h2>
<ul>
<li><p>Quem está mais pra direita (E1, E2, E3) → são aqueles com valores altos nessas variáveis</p></li>
<li><p>Quem está mais pra esquerda (E8, E9, E10…) → são os com valores baixos</p></li>
<li><p>A empresa E12 posiciona-se muito próxima à origem do plano principal, indicando um perfil mediano em todas as variáveis financeiras consideradas.</p>
<ul>
<li>Ela não apresenta características extremas nem para valores altos, nem para valores baixos, sendo portanto uma empresa altamente representativa do centro da distribuição.</li>
</ul></li>
</ul>
<div class="fragment">
<ul>
<li><strong>PC2 (Dim2 = 14.1%):</strong> quase não traz informação nova → setas não sobem muito, elas estão quase horizontais
<ul>
<li>não existe uma segunda dimensão “conceitual” forte</li>
</ul></li>
</ul>
</div>
</section>
<section id="voltando-a-exemplo" class="slide level2">
<h2>Voltando a Exemplo</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a></a><span class="co"># Contribuições das variáveis para a PC1</span></span>
<span id="cb33-2"><a></a><span class="fu">fviz_contrib</span>(acp_R, <span class="at">choice =</span> <span class="st">"var"</span>, <span class="at">axes =</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>

</div>
<img data-src="comp_princ_files/figure-revealjs/unnamed-chunk-16-1.png" width="960" class="r-stretch"></section>
<section id="voltando-ao-exemplo-16" class="slide level2">
<h2>Voltando ao Exemplo</h2>
<ul>
<li>Esse gráfico mostra o quanto cada variável explica/contribui para a formação do primeiro componente principal.
<ul>
<li>Ganho Bruto contribuiu um pouco mais</li>
<li>Ganho Liquido e Patrimonio contribuem praticamente igual e muito próximo</li>
</ul></li>
</ul>
<div class="fragment">
<ul>
<li>A linha vermelha tracejada é a contribuição média esperada (se todas contribuíssem igual).
<ul>
<li>Como temos 3 variáveis → contribuição média = <span class="math inline">\(100\%/3 \approx 33.33\%\)</span></li>
</ul></li>
</ul>
</div>
</section>
<section id="voltando-ao-exemplo-17" class="slide level2">
<h2>Voltando ao Exemplo</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a></a><span class="fu">fviz_contrib</span>(acp_R, <span class="at">choice =</span> <span class="st">"ind"</span>, <span class="at">axes =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>

</div>
<img data-src="comp_princ_files/figure-revealjs/unnamed-chunk-17-1.png" width="960" class="r-stretch"></section>
<section id="voltando-ao-exemplo-18" class="slide level2">
<h2>Voltando ao Exemplo</h2>
<ul>
<li>Esse gráfico mostra quais indivíduos contribuem mais para definir o plano principal da PC, isto é, quais observações estão orientando a direção das componentes principais.</li>
</ul>
<div class="fragment">
<ul>
<li>A empresa E3 é a maior influenciadora da PCA: sua contribuição para o plano principal é muito superior à média (linha vermelha), indicando que ela é um caso extremo na direção da primeira componente. Esse ponto está orientando de forma dominante a estrutura da análise.</li>
</ul>


</div>
</section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">

</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="../../site_libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="../../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="../../site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="../../site_libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="../../site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="../../site_libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="../../site_libs/revealjs/plugin/notes/notes.js"></script>
  <script src="../../site_libs/revealjs/plugin/search/search.js"></script>
  <script src="../../site_libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="../../site_libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': true,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1600,

        height: 900,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    

    <script>

      // htmlwidgets need to know to resize themselves when slides are shown/hidden.

      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current

      // slide changes (different for each slide format).

      (function () {

        // dispatch for htmlwidgets

        function fireSlideEnter() {

          const event = window.document.createEvent("Event");

          event.initEvent("slideenter", true, true);

          window.document.dispatchEvent(event);

        }

    

        function fireSlideChanged(previousSlide, currentSlide) {

          fireSlideEnter();

    

          // dispatch for shiny

          if (window.jQuery) {

            if (previousSlide) {

              window.jQuery(previousSlide).trigger("hidden");

            }

            if (currentSlide) {

              window.jQuery(currentSlide).trigger("shown");

            }

          }

        }

    

        // hookup for slidy

        if (window.w3c_slidy) {

          window.w3c_slidy.add_observer(function (slide_num) {

            // slide_num starts at position 1

            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);

          });

        }

    

      })();

    </script>

    

    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
            const codeEl = trigger.previousElementSibling.cloneNode(true);
            for (const childEl of codeEl.children) {
              if (isCodeAnnotation(childEl)) {
                childEl.remove();
              }
            }
            return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp("http:\/\/professortp\.com\.br\/est014\/");
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>